modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Mrbysco/DiscCord/issues"
license="MIT"

[[mods]]
modId="disccord"
version="${file.jarVersion}"
displayName="DiscCord"
displayURL="https://www.curseforge.com/minecraft/mc-mods/DiscCord"
authors="Mrbysco"
description='''
A mod that allows you to write music URLs on a Custom Record to play in a Jukebox
'''
[[dependencies.disccord]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.disccord]]
modId="forge"
mandatory=true
versionRange="[43.1.0,)"
ordering="NONE"
side="BOTH"